---
language: go
sudo: true
dist: trusty

env:
  global:
    - TF_ACC=1
    - GO111MODULE=on
    - LXD_REMOTE=travis
    - LXD_ADDR=localhost
    - LXD_PORT=8443
    - LXD_GENERATE_CLIENT_CERTS=true
    - LXD_ACCEPT_SERVER_CERTIFICATE=true
    - LXD_SCHEME=https
    - LXD_PASSWORD="the-password"
    - CGO_CFLAGS="-I /usr/src/linux-headers-4.4.0-137/include/uapi -I /usr/src/linux-headers-4.4.0-137/include/"
  matrix:
    - CHANNEL="stable"
    - CHANNEL="candidate"
    - CHANNEL="edge"

addons:
  apt:
    packages:
      - snapd
      - build-essential
      - linux-headers-4.4.0-137

before_install:
  - sudo snap install lxd --channel=${CHANNEL}
  - export PATH=/snap/bin/:${PATH}
  - sudo lxd waitready --timeout 60
  - sudo lxd init --auto --trust-password="${LXD_PASSWORD}" --network-port=8443 --network-address='[::]'
  - sudo chmod 777 /var/snap/lxd/common/lxd/unix.socket

go:
  - '1.12'
  - master

before_script:
  - go get github.com/mitchellh/gox

script:
  - make fmtcheck
  - make vet
  - make test

matrix:
  fast_finish: true
  allow_failures:
    - go: master
    - env: CHANNEL="edge"

before_deploy:
  - make targets

deploy:
  provider: releases
  api_key:
    secure: sfkgrcvaOhvc7lXmyRROGiaSb2YAQjGrBil9FAVX9VRDSO1TPAy9PS7w5Lf1rS05Ifytbtt7sKKWNVeckDXctDS/rFFHu7ONj3qnQq+/O8VlRX8tr0oqzVq48qz4lC/cJ4QjlqNFW1/oNyM55xobQjaNxKsWaHWW826NutdPEIiTgWQgOe9BGgT44AoyYjuFOhb4Bfgbq7Ds4EOSEIkljhmGABzdy5y+YKUcTt0Ta7E9jHticVDNRb+YXl7uyOrQ+9eIMnkIt6imR1rOQ+UVrZWsORhR2yoqXTzkABFdo85Mqs8KPDIcCaCI/ryPJfgpqIrDqQWMHnXP+PrChiE2De0w16HhI+sSnby9Jy1NYFllZLOZ7mcqmamu3HKm+g2By9iEzt8kgg3Lix9zigxOQWiYjO2lOgpNq/fouB73F1BzAxW2UHwgOCE3ciV36oAO6whlPorJ262W+1D4plk1DkugGu7nC8tguBlIZsiGOoenm5/Otp2xKwE12hGT028OkZK2UqNYBngVOG+2PdH0MksnOmhU7DTS6zwy563PIN7wscDHuVxsxRGFLV+l2WZlkkCIUirtenxw88QVlpzI7pbNF45Wu4EpxLEkhOabzRlzjgpkOOPv3JvKuZvBEQnGX72KwltEtpyj51HoWm2M1BJqEn7ZfQ+kyIkqMqQ6hjo=
  file: dist/*.zip
  file_glob: true
  skip_cleanup: true
  on:
    go: '1.12'
    repo: sl1pm4t/terraform-provider-lxd
    tags: true
    condition: $CHANNEL = "stable"
