language: go
sudo: true
dist: trusty

env:
- TF_ACC=1

before_install:
- sudo add-apt-repository -y ppa:ubuntu-lxc/lxd-stable
- sudo apt-get -qq update
- sudo apt-get install -y lxd
- sudo lxd init --auto
- sudo chmod 777 /var/lib/lxd/unix.socket
- 'lxc image copy ubuntu:t local: --alias=ubuntu'
- lxc image list

go:
- 1.7.4

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

deploy:
  provider: releases
  api_key:
    secure: sfkgrcvaOhvc7lXmyRROGiaSb2YAQjGrBil9FAVX9VRDSO1TPAy9PS7w5Lf1rS05Ifytbtt7sKKWNVeckDXctDS/rFFHu7ONj3qnQq+/O8VlRX8tr0oqzVq48qz4lC/cJ4QjlqNFW1/oNyM55xobQjaNxKsWaHWW826NutdPEIiTgWQgOe9BGgT44AoyYjuFOhb4Bfgbq7Ds4EOSEIkljhmGABzdy5y+YKUcTt0Ta7E9jHticVDNRb+YXl7uyOrQ+9eIMnkIt6imR1rOQ+UVrZWsORhR2yoqXTzkABFdo85Mqs8KPDIcCaCI/ryPJfgpqIrDqQWMHnXP+PrChiE2De0w16HhI+sSnby9Jy1NYFllZLOZ7mcqmamu3HKm+g2By9iEzt8kgg3Lix9zigxOQWiYjO2lOgpNq/fouB73F1BzAxW2UHwgOCE3ciV36oAO6whlPorJ262W+1D4plk1DkugGu7nC8tguBlIZsiGOoenm5/Otp2xKwE12hGT028OkZK2UqNYBngVOG+2PdH0MksnOmhU7DTS6zwy563PIN7wscDHuVxsxRGFLV+l2WZlkkCIUirtenxw88QVlpzI7pbNF45Wu4EpxLEkhOabzRlzjgpkOOPv3JvKuZvBEQnGX72KwltEtpyj51HoWm2M1BJqEn7ZfQ+kyIkqMqQ6hjo=
  file: terraform-provider-lxd
  skip_cleanup: true
  on:
    repo: sl1pm4t/terraform-provider-lxd
    tags: true